"""Inicial

Revision ID: 06bc2ae01295
Revises: 
Create Date: 2025-04-28 15:45:21.118345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bc2ae01295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente_model')
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_entrada', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('hora_salida', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('horas_almuerzo', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('horas_trabajadas', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('horas_viaje_ida', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('horas_viaje_vuelta', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_column('horas_viaje_vuelta')
        batch_op.drop_column('horas_viaje_ida')
        batch_op.drop_column('horas_trabajadas')
        batch_op.drop_column('horas_almuerzo')
        batch_op.drop_column('hora_salida')
        batch_op.drop_column('hora_entrada')

    op.create_table('cliente_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cliente_model_pkey'),
    sa.UniqueConstraint('nombre', name='cliente_model_nombre_key')
    )
    # ### end Alembic commands ###
