"""cambiar contrato a boolean

Revision ID: 8f626b62a28a
Revises: 
Create Date: 2025-04-27 15:39:35.344751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f626b62a28a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('centro_costo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_order', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_servicio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linea_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'centros_costo', ['centro_costo_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipos_servicio', ['tipo_servicio_id'], ['id'])
        batch_op.create_foreign_key(None, 'lineas', ['linea_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('linea_id')
        batch_op.drop_column('tipo_servicio_id')
        batch_op.drop_column('service_order')
        batch_op.drop_column('centro_costo_id')
        batch_op.drop_column('contrato')

    # ### end Alembic commands ###
